[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.mypy]
python_version = "3.12"
strict = true

# Disallow dynamic typing
disallow_any_unimported = true
#disallow_any_expr = true
disallow_any_decorated = true
#disallow_any_explicit = true

warn_unreachable = true


[tool.poe.tasks]
ruff-fix = "ruff check livingdex tests --fix-only --exit-zero"
black = "black livingdex tests"
prettier = "npx --no prettier livingdex/templates --write"
prettier-check = "npx --no prettier livingdex/templates --check"
biome-fix = "npx --no @biomejs/biome check livingdex --write"
format = ["ruff-fix", "black", "prettier", "biome-fix"]

mypy = "mypy livingdex tests"
ruff = "ruff check livingdex tests"
biome = "npx --no @biomejs/biome ci --error-on-warnings livingdex"
pytest = "pytest"
all = ["format", "mypy", "ruff", "biome", "pytest"]


[tool.poetry]
name = "livingdex"
version = "0.1.0"
description = ""
authors = ["Parnassius <Parnassius@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.12"
aiohttp = "3.10.5"
aiohttp-jinja2 = "1.6"
typenv = "0.2.0"

[tool.poetry.group.dev.dependencies]
black = "24.8.0"
mypy = "1.11.2"
poethepoet = "0.28.0"
pytest = "8.3.2"
ruff = "0.6.3"

[tool.poetry.scripts]
livingdex = "livingdex.__main__:main"


[tool.pytest.ini_options]
addopts = "--strict-config --strict-markers"
xfail_strict = true


[tool.ruff]
target-version = "py312"

[tool.ruff.lint]
select = [
    "A",     # flake8-builtins
    "ARG",   # flake8-unused-arguments
    "B",     # flake8-bugbear
    "C4",    # flake8-comprehensions
    "DTZ",   # flake8-datetimez
    "E",     # pycodestyle
    "EM",    # flake8-errmsg
    "F",     # pyflakes
    "I",     # isort
    "ICN",   # flake8-import-conventions
    "ISC",   # flake8-implicit-str-concat
    "N",     # pep8-naming
    "PGH",   # pygrep-hooks
    "PTH",   # flake8-use-pathlib
    "RET",   # flake8-return
    "RUF",   # Ruff-specific rules
    "T10",   # flake8-debugger
    "TID",   # flake8-tidy-imports
    "TRY",   # tryceratops
    "UP",    # pyupgrade
    "W",     # pycodestyle
    "YTT",   # flake8-2020
]
ignore = [
    "A003",  # builtin-attribute-shadowing
]
fixable = [
    "I",     # isort
    "F401",  # unused-import
    "TID",   # flake8-tidy-imports
    "UP",    # pyupgrade
]
dummy-variable-rgx = "^_$"

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.lint.isort]
required-imports = ["from __future__ import annotations"]
split-on-trailing-comma = false
