from __future__ import annotations

import struct
from pathlib import Path


def parse(save: Path, sub_parser: str) -> list[list[str]]:
    assert sub_parser == ""

    boxes = []
    with save.open("rb") as f:
        for box_index in range(14):
            ofs = 0x4000 if box_index < 7 else 0x6000
            ofs += 0x450 * (box_index % 7)
            f.seek(ofs)
            pokemon_count = f.read(1)[0]
            box = []
            for i, pokemon_index in enumerate(f.read(pokemon_count)):
                pokemon = _indices[pokemon_index]
                if pokemon == "unown":
                    f.seek(ofs + 0x16 + i * 0x20 + 0x15)
                    (dvs,) = struct.unpack("<H", f.read(2))
                    letter = (
                        (((dvs >> 5) & 0x3) << 6)
                        + (((dvs >> 1) & 0x3) << 4)
                        + (((dvs >> 13) & 0x3) << 2)
                        + ((dvs >> 9) & 0x3)
                    )
                    letters = "abcdefghijklmnopqrstuvwxyz"
                    pokemon = f"unown-{letters[letter//10]}"
                box.append(pokemon)
            boxes.append(box)

    return boxes


_indices = {
    0x01: "bulbasaur",
    0x02: "ivysaur",
    0x03: "venusaur",
    0x04: "charmander",
    0x05: "charmeleon",
    0x06: "charizard",
    0x07: "squirtle",
    0x08: "wartortle",
    0x09: "blastoise",
    0x0A: "caterpie",
    0x0B: "metapod",
    0x0C: "butterfree",
    0x0D: "weedle",
    0x0E: "kakuna",
    0x0F: "beedrill",
    0x10: "pidgey",
    0x11: "pidgeotto",
    0x12: "pidgeot",
    0x13: "rattata",
    0x14: "raticate",
    0x15: "spearow",
    0x16: "fearow",
    0x17: "ekans",
    0x18: "arbok",
    0x19: "pikachu",
    0x1A: "raichu",
    0x1B: "sandshrew",
    0x1C: "sandslash",
    0x1D: "nidoran-f",
    0x1E: "nidorina",
    0x1F: "nidoqueen",
    0x20: "nidoran-m",
    0x21: "nidorino",
    0x22: "nidoking",
    0x23: "clefairy",
    0x24: "clefable",
    0x25: "vulpix",
    0x26: "ninetales",
    0x27: "jigglypuff",
    0x28: "wigglytuff",
    0x29: "zubat",
    0x2A: "golbat",
    0x2B: "oddish",
    0x2C: "gloom",
    0x2D: "vileplume",
    0x2E: "paras",
    0x2F: "parasect",
    0x30: "venonat",
    0x31: "venomoth",
    0x32: "diglett",
    0x33: "dugtrio",
    0x34: "meowth",
    0x35: "persian",
    0x36: "psyduck",
    0x37: "golduck",
    0x38: "mankey",
    0x39: "primeape",
    0x3A: "growlithe",
    0x3B: "arcanine",
    0x3C: "poliwag",
    0x3D: "poliwhirl",
    0x3E: "poliwrath",
    0x3F: "abra",
    0x40: "kadabra",
    0x41: "alakazam",
    0x42: "machop",
    0x43: "machoke",
    0x44: "machamp",
    0x45: "bellsprout",
    0x46: "weepinbell",
    0x47: "victreebel",
    0x48: "tentacool",
    0x49: "tentacruel",
    0x4A: "geodude",
    0x4B: "graveler",
    0x4C: "golem",
    0x4D: "ponyta",
    0x4E: "rapidash",
    0x4F: "slowpoke",
    0x50: "slowbro",
    0x51: "magnemite",
    0x52: "magneton",
    0x53: "farfetchd",
    0x54: "doduo",
    0x55: "dodrio",
    0x56: "seel",
    0x57: "dewgong",
    0x58: "grimer",
    0x59: "muk",
    0x5A: "shellder",
    0x5B: "cloyster",
    0x5C: "gastly",
    0x5D: "haunter",
    0x5E: "gengar",
    0x5F: "onix",
    0x60: "drowzee",
    0x61: "hypno",
    0x62: "krabby",
    0x63: "kingler",
    0x64: "voltorb",
    0x65: "electrode",
    0x66: "exeggcute",
    0x67: "exeggutor",
    0x68: "cubone",
    0x69: "marowak",
    0x6A: "hitmonlee",
    0x6B: "hitmonchan",
    0x6C: "lickitung",
    0x6D: "koffing",
    0x6E: "weezing",
    0x6F: "rhyhorn",
    0x70: "rhydon",
    0x71: "chansey",
    0x72: "tangela",
    0x73: "kangaskhan",
    0x74: "horsea",
    0x75: "seadra",
    0x76: "goldeen",
    0x77: "seaking",
    0x78: "staryu",
    0x79: "starmie",
    0x7A: "mr-mime",
    0x7B: "scyther",
    0x7C: "jynx",
    0x7D: "electabuzz",
    0x7E: "magmar",
    0x7F: "pinsir",
    0x80: "tauros",
    0x81: "magikarp",
    0x82: "gyarados",
    0x83: "lapras",
    0x84: "ditto",
    0x85: "eevee",
    0x86: "vaporeon",
    0x87: "jolteon",
    0x88: "flareon",
    0x89: "porygon",
    0x8A: "omanyte",
    0x8B: "omastar",
    0x8C: "kabuto",
    0x8D: "kabutops",
    0x8E: "aerodactyl",
    0x8F: "snorlax",
    0x90: "articuno",
    0x91: "zapdos",
    0x92: "moltres",
    0x93: "dratini",
    0x94: "dragonair",
    0x95: "dragonite",
    0x96: "mewtwo",
    0x97: "mew",
    0x98: "chikorita",
    0x99: "bayleef",
    0x9A: "meganium",
    0x9B: "cyndaquil",
    0x9C: "quilava",
    0x9D: "typhlosion",
    0x9E: "totodile",
    0x9F: "croconaw",
    0xA0: "feraligatr",
    0xA1: "sentret",
    0xA2: "furret",
    0xA3: "hoothoot",
    0xA4: "noctowl",
    0xA5: "ledyba",
    0xA6: "ledian",
    0xA7: "spinarak",
    0xA8: "ariados",
    0xA9: "crobat",
    0xAA: "chinchou",
    0xAB: "lanturn",
    0xAC: "pichu",
    0xAD: "cleffa",
    0xAE: "igglybuff",
    0xAF: "togepi",
    0xB0: "togetic",
    0xB1: "natu",
    0xB2: "xatu",
    0xB3: "mareep",
    0xB4: "flaaffy",
    0xB5: "ampharos",
    0xB6: "bellossom",
    0xB7: "marill",
    0xB8: "azumarill",
    0xB9: "sudowoodo",
    0xBA: "politoed",
    0xBB: "hoppip",
    0xBC: "skiploom",
    0xBD: "jumpluff",
    0xBE: "aipom",
    0xBF: "sunkern",
    0xC0: "sunflora",
    0xC1: "yanma",
    0xC2: "wooper",
    0xC3: "quagsire",
    0xC4: "espeon",
    0xC5: "umbreon",
    0xC6: "murkrow",
    0xC7: "slowking",
    0xC8: "misdreavus",
    0xC9: "unown",
    0xCA: "wobbuffet",
    0xCB: "girafarig",
    0xCC: "pineco",
    0xCD: "forretress",
    0xCE: "dunsparce",
    0xCF: "gligar",
    0xD0: "steelix",
    0xD1: "snubbull",
    0xD2: "granbull",
    0xD3: "qwilfish",
    0xD4: "scizor",
    0xD5: "shuckle",
    0xD6: "heracross",
    0xD7: "sneasel",
    0xD8: "teddiursa",
    0xD9: "ursaring",
    0xDA: "slugma",
    0xDB: "magcargo",
    0xDC: "swinub",
    0xDD: "piloswine",
    0xDE: "corsola",
    0xDF: "remoraid",
    0xE0: "octillery",
    0xE1: "delibird",
    0xE2: "mantine",
    0xE3: "skarmory",
    0xE4: "houndour",
    0xE5: "houndoom",
    0xE6: "kingdra",
    0xE7: "phanpy",
    0xE8: "donphan",
    0xE9: "porygon2",
    0xEA: "stantler",
    0xEB: "smeargle",
    0xEC: "tyrogue",
    0xED: "hitmontop",
    0xEE: "smoochum",
    0xEF: "elekid",
    0xF0: "magby",
    0xF1: "miltank",
    0xF2: "blissey",
    0xF3: "raikou",
    0xF4: "entei",
    0xF5: "suicune",
    0xF6: "larvitar",
    0xF7: "pupitar",
    0xF8: "tyranitar",
    0xF9: "lugia",
    0xFA: "ho-oh",
    0xFB: "celebi",
    0xFD: "egg",
}
